force-app/main/default/objects/Account/fields/Account_Wallet__c.field-meta.xml
<CustomField>
    <fullName>Account_Wallet__c</fullName>
    <label>Account_Wallet</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Wallet__c.field-meta.xml
<CustomField>
    <fullName>Contact_Wallet__c</fullName>
    <label>Contact_Wallet</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChangeAccountWallet.cls
public without sharing class ChangeAccountWallet {
    
    public static void isBudgetUpdate(List<Contact> newContacts, List<Contact> oldContacts){
        Map<Contact, Double> contactsAfterWalletUpdate = new Map<Contact, double>();
        for(Contact newContact : newContacts){
            for(Contact oldContact : oldContacts){
                if(oldContact.id == newContact.id && oldContact.Contact_Wallet__c != newContact.Contact_Wallet__c){
                    contactsAfterWalletUpdate.put(newContact, newContact.Contact_Wallet__c - oldContact.Contact_Wallet__c);
                }
            }   
        }

        updateAccountBudget(contactsAfterWalletUpdate);
    }

    private static void updateAccountBudget(Map<Contact,Double> contactsAfterWalletUpdate){
        List<Account> allAccounts = [SELECT Account_Wallet__c, id, Budget__c FROM Account];
        List<Account> accountsToUpdate = new List<Account>();
        for(Account account : allAccounts){
            for(Contact contact : contactsAfterWalletUpdate.keySet()){
                if(account.id == contact.AccountId){
                    account.Account_Wallet__c = account.Account_Wallet__c + contactsAfterWalletUpdate.get(contact);
                    account.Expenses__c = account.Budget__c - account.Account_Wallet__c;
                    accountsToUpdate.add(account);
                }
            }
        }
        update accountsToUpdate;
    }
}