force-app/main/default/objects/Account/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Car Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_price__c</fullName>
    <label>Purchase price</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChangeAccountBudget.cls
public without sharing class ChangeAccountBudget {
    public static void increaseBudget(List<Car__c> cars){
        List<Account> accountList = new List<Account>();
        List<id> idList = new List<id>();
        for(Car__c car:cars){
            idList.add(car.Contacts__c);
        }
        List<Contact> contacts = [SELECT Id, Account.Budget__c, (SELECT Value__c, Purchase_price__c FROM Cars__r) FROM Contact WHERE id =: idList];
        System.debug(contacts.Value__c);
        System.debug(contacts.Purchase_price__c);
        // for(Car__c car:cars){
            // Contact carContact=[SELECT AccountId FROM Contact WHERE id=:car.Contacts__c];
            // Account carAccount=[SELECT, (SELECT Id FROM Contacts) Budget__c FROM Account WHERE Id=:carContact.AccountId];
            // Car__r.Contact__r.Accounta (SELECT Value__c, Purchase_price__c from Cars),

            //[SELECT Id, (SELECT Id .... from car__r), FROM Contact WHERE Id =: car.Contact__c];
            // Car__c car = [SELECT Id, Contact__r.Id, Contact__r.AccountId FROM Car__c WHERE Id =: ]
            //carAccount.Budget__c = carAccount.Budget__c + car.Value__c;
            
            //accountList.add(carAccount);
        // }
        // update(accountList);
    }
    public static void reductionBudget(List<Car__c> cars){
        List<Account> accountList=new List<Account>();
        //List<Contact> contacts = [SELECT Id, (SELECT Value__c, Purchase_price__c from Car__r), (SELECT Budget__c FROM Account) FROM Contact WHERE Id IN :cars.Contacts__c];
        //System.debug(contacts);
        for(Car__c car:cars){
            Contact carContact=[SELECT AccountId FROM Contact WHERE id=:car.Contacts__c];
            Account carAccount=[SELECT Budget__c FROM Account WHERE Id=:carContact.AccountId];

            carAccount.Budget__c = carAccount.Budget__c - car.Purchase_price__c;
            
            accountList.add(carAccount);
        }
        update(accountList);
    }
}