force-app/main/default/objects/Account/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_budget__c.field-meta.xml
<CustomField>
    <fullName>Contact_budget__c</fullName>
    <label>Contact_budget_value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChangeAccountBudgets.cls
public without sharing class ChangeAccountBudgets {

    public static void isBudgetUpdate(List<Contact> newContacts, List<Contact> oldContacts){
        Map<Contact, Double> contactsAfterBudgetUpdate = new Map<Contact, double>();
        List<Account> allAccounts = [SELECT Budget__c, id FROM Account];
        List<Account> accountsToUpdate = new List<Account>();
        for(Contact newContact : newContacts){
            for(Contact oldContact : oldContacts){
                if(oldContact.id == newContact.id && oldContact.Contact_budget__c != newContact.Contact_budget__c){
                    contactsAfterBudgetUpdate.put(newContact, newContact.Contact_budget__c - oldContact.Contact_budget__c);
                }
            }   
        }

        for(Account account : allAccounts){
            for(Contact contact : contactsAfterBudgetUpdate.keySet()){
                if(account.id == contact.AccountId){
                    System.debug(contactsAfterBudgetUpdate.get(contact));
                    System.debug(account.Budget__c);
                    account.Budget__c = account.Budget__c + contactsAfterBudgetUpdate.get(contact);
                    System.debug(account.Budget__c);
                    accountsToUpdate.add(account);
                }
            }
        }
        update accountsToUpdate;
    }
}