force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Car Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Fuel__c.field-meta.xml
<CustomField>
    <fullName>Fuel__c</fullName>
    <label>Fuel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Wrapper.cls
public with sharing class Wrapper {

    @AuraEnabled(cacheable=true)
    public static List<ContactWrapperClass> fetchWrapperData(String AccountId){

        Account AccountIds = [SELECT id FROM Account WHERE id=:AccountId];
        List<ContactWrapperClass> wrapperList = new List<ContactWrapperClass>();
        List<Contact> ContactNameList = [SELECT id, name FROM Contact WHERE AccountId =:AccountIds.id];

        Set<id> contactsIds = new Set<id>();
        for(Contact contact: ContactNameList){
            contactsIds.add(contact.id);
        }

        List<Car__c> carList = [SELECT Name__c, Fuel__c,Contacts__c FROM Car__c WHERE Contacts__c IN :contactsIds];
        
        for(Car__c car : carList){
            for(Contact contact : ContactNameList){
                if(car.Contacts__c == contact.id){
                    wrapperList.add(new ContactWrapperClass(car, contact.name));
                }
            }
        }
        return wrapperList;
    }

    public class ContactWrapperClass {
        @AuraEnabled
        public Car__c car;
        @AuraEnabled
        public String Contact_Name;
        @AuraEnabled
        public String Car_name;
        @AuraEnabled
        public String Car_Fuel;
 
        public ContactWrapperClass(Car__c car, String  name){
            this.car = car;
            this.Contact_Name = name;
            this.Car_name = car.Name__c;
            this.Car_Fuel = car.Fuel__c;
        }
    }
}