force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Car Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Fuel__c.field-meta.xml
<CustomField>
    <fullName>Fuel__c</fullName>
    <label>Fuel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CarAPI.cls
@RestResource( urlMapping = '/Car/*')
Global class CarAPI {

    @HttpGet
    global static List<Car__c> getCarFromId(){
        RestRequest request = RestContext.request;
        String carId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);

        RestResponse response = new RestResponse();
        List<Car__c> carList;

        if(carId.length() == 0){
            RestContext.response.statusCode = 404;
        }else{
            try{
                carList = [SELECT Id, Name__c, Fuel__c, Value__c FROM Car__c WHERE id =:carId];
            RestContext.response.responseBody = Blob.valueof(JSON.serialize(carList));
            }catch(Exception e){
                System.debug(' Exception '+ e.getMessage());
            }
        }
        return carList;
    }
}