force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Car Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Wallet__c.field-meta.xml
<CustomField>
    <fullName>Contact_Wallet__c</fullName>
    <label>Contact_Wallet</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChangeContactWalletValue.cls
public without sharing class ChangeContactWalletValue {

    public static void increaseWallet(Map<id, Car__c> newCars){

        List<Contact> contactsToUpdate = new List<Contact>();
        Set<id> contactIds = getContactIdFromCar(newCars);
        List<Contact> contactFromCarId = [SELECT  id, Contact_Wallet__c FROM Contact WHERE id IN (SELECT Contacts__c FROM Car__c WHERE Contacts__c IN :contactIds)];

        for( Contact contact : contactFromCarId) {
            for( Car__c car : newCars.values()) {
                if(( contact.id).equals(car.Contacts__c)){
                    contact.Contact_Wallet__c += car.value__c;
                    contactsToUpdate.add(contact);
                }
            }
        }
        update contactsToUpdate;
    }

    public static void reductionWallet(Map<id, Car__c> newCars){
        List<Contact> contactsToUpdate = new List<Contact>();
        Set<id> contactIds = getContactIdFromCar(newCars);
        List<Contact> contactFromCarId = [SELECT  id, Contact_Wallet__c FROM Contact WHERE id IN (SELECT Contacts__c FROM Car__c WHERE Contacts__c IN :contactIds)];

        for( Contact contact : contactFromCarId) {
            for( Car__c car : newCars.values()) {
                if(( contact.id).equals(car.Contacts__c)){
                    contact.Contact_Wallet__c -= car.value__c;
                    contactsToUpdate.add(contact);
                }
            }
        }
        update contactsToUpdate;
    }
    private static Set<Id> getContactIdFromCar(Map<id,Car__c> CarsMap){
        Set<id> contactIds = new Set<id>();
        for(Car__c car: newCars.values()) {
            contactIds.add(car.Contacts__c);
        }
        return contactIds;
    }
}